name: Trigger auto deployment for app-event-capture-reinvent

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/app-event-capture-reinvent-AutoDeployTrigger-ff297112-c9cc-4a0a-b87f-77873139d42e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.APPEVENTCAPTUREREINVENT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: theacr.azurecr.io
          registryUsername: ${{ secrets.APPEVENTCAPTUREREINVENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPEVENTCAPTUREREINVENT_REGISTRY_PASSWORD }}
          containerAppName: app-event-capture-reinvent
          resourceGroup: rg-product-event-capture-reinvent
          imageToBuild: theacr.azurecr.io/app-event-capture-reinvent:${{ github.sha }}
          
            

     

