name: Trigger auto deployment for app-event-capture-reinvent

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/app-event-capture-reinvent-AutoDeployTrigger-1b949e7b-991f-4f54-ae0e-4c4f22ded599.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.APPEVENTCAPTUREREINVENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPEVENTCAPTUREREINVENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPEVENTCAPTUREREINVENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: theacr.azurecr.io
          registryUsername: ${{ secrets.APPEVENTCAPTUREREINVENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPEVENTCAPTUREREINVENT_REGISTRY_PASSWORD }}
          containerAppName: app-event-capture-reinvent
          resourceGroup: rg-product-event-capture-reinvent
          imageToBuild: theacr.azurecr.io/app-event-capture-reinvent:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


